name: Deploy to Amazon EC2

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAZJNUPWVQCKGU6ALZ
        aws-secret-access-key: 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
        aws-region: us-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build
      run: docker build -t abhay .
    - name: tag
      run: docker tag abhay:latest 638718031200.dkr.ecr.us-east-1.amazonaws.com/abhay:latest
    - name: push
      run: docker push 638718031200.dkr.ecr.us-east-1.amazonaws.com/abhay:latest
      
    - name: terraform directory
      run : mkdir terraform
    - name: ading file
      run : cp terraform1.tf terraform
    - uses: actions/checkout@v3
    - name: creating directory
      run: mkdir hello
    - name: building image
      run: sudo apt-get install unzip
    - name: version
      run : wget https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    - name: unzip
      run: unzip terraform_1.0.7_linux_amd64.zip
    - name: moving
      run: sudo mv terraform /hello
    - name: version 1
      run: terraform --version
    - name: intializing terraform
      run: terraform init
    - name: building
      run: terraform apply -auto-approve
    - name: pulling
      run: ddocker pull 638718031200.dkr.ecr.us-east-1.amazonaws.com/abhay:latest
    - name: running image
      run: docker run 638718031200.dkr.ecr.us-east-1.amazonaws.com/abhay:latest
    - name: showing a list all container
      run: docker ps -a
    - name: to start containers
      run: docker ps -q -a
    - name: showing a list of running containers
      run: docker ps
